--- #YAML:1.0
name:         Test-Weaken
version:             3.005_002
abstract:            Test that freed memory objects were, indeed, freed
author:              
    - Jeffrey Kegler
generated_by:        Jeffrey Kegler
license: perl
distribution_type:   module
no_index:
    directory:
        - inc
        - t
        - example
        - author.t
        - save
    namespace:
        - Test::Weaken::Internal
requires:     
    Test::More:                    0
provides:
    Test::Weaken:
        file: lib/Test/Weaken.pm
        version: 3.005_002
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
